config/routes.rb
Rails.application.routes.draw do
  root 'stationary_pages#index'
  get 'about' => 'stationary_pages#about'
  get 'contact' => 'stationary_pages#contact'
  get 'log_out' => 'sessions#destroy'

  resources :users do
    resources :toys
  end
  resources :toys
  resources :sessions

end

app/models/toy.rb
class Toy < ActiveRecord::Base
    belongs_to :user
    validates :name, presence:true, length: { minimum: 2 }
    validates :manufacturer, presence: true
    validates :category, presence: true
    
    #Used for image upload | thoughtbot/paperclip gem. 
    has_attached_file :image, styles: {
        thumb: '100x100>',
        square: '200x200#',
        medium: '300x300>'
    }
    
    #image upload validations.
    validates_attachment :image, :less_than => 5.megabytes, presence: true, 
    content_type: { :content_type => ["image/jpg", "image/jpeg", "image/gif", "image/png"] }
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    #after_save :user_notification
    
    has_many :toys
    validates :name, presence: true, length: { minimum: 3 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, 
                                      format: { with: VALID_EMAIL_REGEX },
                                      length: { maximum: 255 }
    has_secure_password
    validates :password, length: { minimum: 6 }
    
    private
    
        def user_notification
            BrinquedoMailer.greeting(self).deliver
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "You have successfuly logged in"
      log_in(user)
      redirect_to user
    else
      flash[:alert] = "Invalid email or password"
      redirect_to new_session_path
    end
  end

  def destroy
    flash[:success] = "Logged out"
    log_out if logged_in?
    redirect_to root_url
  end
  
  private
  
    
end

app/controllers/stationary_pages_controller.rb
class StationaryPagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :logged_in?, only: [:create, :destroy]
  before_action :get_toy, only: [:edit, :update]
  
  def new
    @toy = current_user.toys.build
  end

  def create
    @toy = current_user.toys.build(toy_params)
    if @toy.save
      flash[:success] = "Toy created!"
      redirect_to user_toy_path(current_user, @toy)
    else
      flash[:alert] = "Something went wrong, try again"
      redirect_to new_user_toy_path(current_user)
    end
  end 

  def show
    #Gets a toy to display in the show page.
    @toy = Toy.find_by(id: params[:id])
  end

  def edit
    
  end

  def update
    if @toy.update_attributes(toy_params)
      flash[:success] = "Toy updated"
      redirect_to current_user
    else
      render 'edit'
    end
  end

  def index
    #Displays the toys of all the users
    @toys = Toy.all
  end

  def destroy
    @toy = current_user.toys.find_by(id: params[:id])
    if @toy.present?
      @toy.destroy
      flash[:success] = "Toy deleted"
    end
    redirect_to current_user
  end
  
  private
   
   def toy_params
     params.require(:toy).permit(:name, :manufacturer, :category, :image)
   end
   
   def get_toy
    @toy = current_user.toys.find(params[:id])
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    #provides an @user IVAR for the form helper.
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:success] = "You have successfuly signed up"
      log_in(@user)
      redirect_to user_path(@user)
    else
      flash[:alert] = "Sign up failed"
      render 'new'
    end
  end
  
  def show
    #only shows the toys that are owned by the current user.
    @toys = current_user.toys.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update 
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile successfuly updated"
      redirect_to @user
    else
      flash.now[:alert] = "Something is wrong"
      render 'edit'
    end
  end
  
  def index
    @users = User.all
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to root_url
  end
  
  private
    #setting strong parameters (Required in rails 4)
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
    #Logs the user in
    def log_in(user)
      session[:user_id] = user.id
    end
    
    def log_out
      session.delete(:user_id)
    end
    
    #Checks to see if there is a logged in user
    def logged_in?
        if !session[:user_id].nil?
            return true
        else
            return false
        end
    end
    
    #Returns the current user in the session.
    def current_user
        current_user = User.find_by(id: session[:user_id])
    end
end

app/helpers/stationary_pages_helper.rb
module StationaryPagesHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <div data-alert class="alert-box <%= message_type %>">
        <%= message %>
        <a href="#" class="close">&times;</a>
    </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="contain-to-grid">
    <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
            <li class="name">
              <h1 id="bar-title"><%= link_to "Brinquedoteca", root_path %></h1>
            </li>
            <% if logged_in? %>
            <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
            <ul class="right button-group">
                <li><%= link_to "Add toy", new_user_toy_path(current_user), class: "button" %></li>
                <li><%= link_to "Profile", user_path(current_user), class: "button" %></li>
                <li><%= link_to "Settings", edit_user_path(current_user), class: "button" %></li>
                <li><%= link_to "Toy index", user_toys_path(current_user), class: "button" %></li>
                <li><%= link_to "Users index", users_path, class: "button" %></li>
                <li><%= link_to "log out", log_out_path, class: "button alert" %></li>
                <% end %>
            </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <% if !current_page?(root_path) %>
          <%= render 'layouts/header' %>
      <% end %>
      <%= render 'layouts/flash' %>
      <%= yield %>
      <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/shared/_error.html.erb
<% if @user.errors.any? %>
    <div data-alert class="alert-box alert radius">
        There are <%= pluralize(@user.errors.count, "error") %>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/stationary_pages/about.html.erb
<h1>StationaryPages#about</h1>
<p>Find me in app/views/stationary_pages/about.html.erb</p>

app/views/stationary_pages/contact.html.erb
<h1>StationaryPages#contact</h1>
<p>Find me in app/views/stationary_pages/contact.html.erb</p>

app/views/stationary_pages/index.html.erb
<% provide(:title, "Brinquedoteca") %>
<div class="container">
  <header class="titleHeader">
    <h1 class="title">Brinquedoteca</h1>
  </header>
  <div class="home-info">
    <div class="row">
  		<div class="small-12 large-6 columns">
  		  <%= link_to "Sign Up", new_user_path, class: "button large" %>
  		  <%= link_to "Login", new_session_path, class: "button large" %>  
  		</div>
  		<div class="small-12 large-6 columns">
  			<div class="panel">
  			  <h1>Welcome!</h1>
  			  <p>Brinquedoteca is a web based, open source toy inventory system for special education professionals.</p>
  			  <p>Brinquedoteca is still under development. Check back for updates.</p>
  			</div>
  		</div>
  	</div>
  </div>
  <div class="footer-info">
    <nav class="breadcrumbs">
      <li>Developed by: Christian Machado Brandalise</li>
      <li><%= link_to "About", "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
    </nav>
  </div>
</div>
    

app/views/toys/edit.html.erb
<div class="row">
    <div class="small 12 large-6 large-centered columns">
        <%= form_for([current_user, @toy], html: { multipart: true }) do |f| %>
         <%= f.label :name %>
         <%= f.text_field :name %>
         
         <%= f.label :manufacturer %>
         <%= f.text_field :manufacturer %>
         
         <%= f.label :category %>
         <%= f.select :category, options_for_select(%w[Educational Therapeutic Recreational Other]) %>
         
         <%= f.label :image %>
         <%= f.file_field :image %>
         
         <%= f.submit "Update toy", class: 'button' %>
         <% end %>
    </div>
</div>

app/views/toys/index.html.erb
<div class="row">
    <div class="small-6 large-centered columns">
        <h1>Toy index (<%= @toys.count %>)</h1>
        <% @toys.each do |toy| %>
        <% user = User.find_by(id: toy.user_id) %>
        <table>
            <thead>
                <th>Image</th>
                <th>Name</th>
                <th>Manufacturer</th>
                <th>Category</th>
            </thead>
            <tbody>
                <tr>
                    <td><%= image_tag toy.image.url, class: "th" %></td>
                    <td><%= toy.name %></td>
                    <td><%= toy.manufacturer %></td>
                    <td><%= toy.category %></td>
                </tr>
                <tr>
                    <td colspan="5">
                        <p id="tiny">Created by: <%= user.name %> | <%= time_ago_in_words(toy.created_at) %> ago.</p>
                        <%= link_to "view toy", toy_path(toy), class: "button tiny" %>
                        <% if current_user.id == toy.user_id %> 
                            <%= link_to "delete toy", user_toy_path(current_user, toy), method: :delete, class: "button alert tiny" %>
                        <% end %>
                    </td>
                </tr>
            </tbody>
        </table>
        
        <% end %>
    </div>
</div>

app/views/toys/new.html.erb
<div class="row">
  <div class="small 12 large-6 large-centered columns">
    <h3>Add new toy</h3>
    <%= form_for([current_user, @toy], html: { multipart: true }) do |f| %>
    
     <%= f.label :name %>
     <%= f.text_field :name %>
     
     <%= f.label :manufacturer %>
     <%= f.text_field :manufacturer %>
     
     <%= f.label :category %>
     <%= f.select :category, options_for_select(%w[Educational Therapeutic Recreational Other]) %>
     
     <%= f.label :image %>
     <%= f.file_field :image %>
     
     <%= f.submit "Submit new toy", class: "button" %>
    <% end %>
  </div>
</div>

app/views/toys/show.html.erb
<div class="row">
    <div class="small-6 large-centered columns">
        <h1><%= @toy.manufacturer %> <%= @toy.name %></h1>
        <table>
            <thead>
                <th>Image</th>
                <th>Name</th>
                <th>Manufacturer</th>
                <th>Category</th>
            </thead>
            <tbody>
                <tr>
                    <td><%= image_tag @toy.image.url %></td>
                    <td><%= @toy.name %></td>
                    <td><%= @toy.manufacturer %></td>
                    <td><%= @toy.category %></td>
                </tr>
            </tbody>
        </table>
        <% if current_user.id == @toy.user_id %>
            <%= link_to "edit toy", edit_user_toy_path(current_user, @toy), class: "button tiny" %>
            <%= link_to "delete toy", user_toy_path(current_user, @toy), method: :delete, class: "button alert tiny" %>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="small 12 large-6 large-centered columns">
    <h1>Edit your information</h1>
    <%= render 'shared/error' %>
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :email %>
      <%= f.email_field :email %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>
      
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.submit "Save Changes", class: 'button' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
    <div class="small-12 large-6 large-centered columns">
      <h1>Users Index (<%= @users.count %>)</h1>
        <% @users.each do |user| %>
            <table>
                <thead>
                    <tr>
                        <th>User ID</th>
                        <th>Name</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><%= user.id %></td>
                        <td><%= user.name %></td>
                        <td><%= user.email %></td>
                    </tr>
                </tbody>
            </table>
        <%end%>
    </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="small 12 large-6 large-centered columns">
    <h1>Sign Up</h1>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error' %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :email %>
      <%= f.email_field :email %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>
      
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.submit "Sign Up", class: "button [tiny small large]" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <div class="large-6 columns">
       <h4>Welcome back <%= current_user.name %>!</h4>
       
       <%= link_to "Add new toy", new_user_toy_path(current_user), class: 'button' %>
       <%= link_to "View all toys", user_toys_path(current_user), class: 'button' %>
    </div>
    <div class="large-6 columns">
        <div>
            <% if @toys.any? %>
               <h4>Your toys</h4>
               <% @toys.each do |toy| %>
               <table>
                   <thead>
                        
                       <tr>
                           <th width="150">Image</th>
                           <th>ID</th>
                           <th>Name</th>
                           <th>Manufacturer</th>
                           <th>Category</th>
                       </tr>
                   </thead>
                   <tbody>
                       <tr>
                          <td><%= image_tag toy.image.url, class: "th" %></td>
                          <td><%= toy.id %></td>
                          <td><%= toy.name %></td>
                          <td><%= toy.manufacturer%></td>
                          <td><%= toy.category %></td> 
                       </tr>
                       <tr>
                           <td colspan="5">
                              <p id="tiny">created <%= time_ago_in_words(toy.created_at) %> ago. </p>
                              <%= link_to "view toy", toy_path(toy), class: "button tiny" %>
                              <%= link_to "edit toy", edit_user_toy_path(current_user, toy), class: "button tiny" %>
                              <%= link_to "delete toy", user_toy_path(current_user, toy), method: :delete, class: "button alert tiny" %> 
                           </td>
                       </tr>
                   </tbody>
               </table>
               <% end %>
            <% else %>
                <h3>You currently have no toys</h3>
            <% end %>
        </div>
    </div>
</div>